### ISSUE TITLE
trying to draw too large bitmap.

### ISSUE THREAD

**Issue by cdfmlr** [musharing-team/Musharing-Android#13]
```
2019-11-24 22:26:01.878 18333-18333/com.mine.musharing E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mine.musharing, PID: 18333
    java.lang.RuntimeException: Canvas: trying to draw too large(132710400bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
        at android.view.View.getDrawableRenderNode(View.java:19663)
        at android.view.View.drawBackground(View.java:19597)
        at android.view.View.draw(View.java:19380)
        at android.view.View.updateDisplayListIfDirty(View.java:18318)
        at android.view.View.draw(View.java:19106)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
        at android.view.View.updateDisplayListIfDirty(View.java:18304)
        at android.view.View.draw(View.java:19106)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
        at android.view.View.updateDisplayListIfDirty(View.java:18304)
        at android.view.View.draw(View.java:19106)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
        at android.view.View.updateDisplayListIfDirty(View.java:18304)
        at android.view.View.draw(View.java:19106)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
        at android.view.View.updateDisplayListIfDirty(View.java:18304)
        at android.view.View.draw(View.java:19106)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
        at android.view.View.draw(View.java:19392)
        at com.android.internal.policy.DecorView.draw(DecorView.java:987)
        at android.view.View.updateDisplayListIfDirty(View.java:18318)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:676)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:682)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:790)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3097)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2890)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2443)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1452)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6960)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
        at android.view.Choreographer.doCallbacks(Choreographer.java:737)
        at android.view.Choreographer.doFrame(Choreographer.java:669)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:911)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
```

解决方案参考：
- https://blog.csdn.net/u011047085/article/details/88179241
- https://www.cnblogs.com/spring87/p/7645625.html

**Comment by cdfmlr** [comment]
already fixed in  c2c57354b785fae6c55cba440caa7f08674ef57c
