### ISSUE TITLE
使用弃用的 getDeviceId 导致闪退

### ISSUE THREAD

**Issue by cdfmlr** [musharing-team/Musharing-Android#9]
`getDeviceId` 等获取不可变id的方法已经被弃用。

在储存信息加密的过程中调用 `TelephonyManager.getDeviceId` 可能获取失败导致软件无法使用：

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mine.musharing, PID: 29808
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mine.musharing/com.mine.musharing.activities.LoginActivity}: java.lang.SecurityException: getDeviceId: Neither user 10251 nor current process has android.permission.READ_PHONE_STATE.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2982)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1769)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
     Caused by: java.lang.SecurityException: getDeviceId: Neither user 10251 nor current process has android.permission.READ_PHONE_STATE.
        at android.os.Parcel.readException(Parcel.java:2013)
        at android.os.Parcel.readException(Parcel.java:1959)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:5024)
        at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1047)
        at com.mine.musharing.activities.LoginActivity.onCreate(LoginActivity.java:74)
        at android.app.Activity.performCreate(Activity.java:7125)
        at android.app.Activity.performCreate(Activity.java:7116)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2935)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1769) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826) 
```

需要实现替代方案。

**Comment by cdfmlr** [comment]
已在 856f920f0269d48475ad16843dbb9efe0e7f51bb 中更改了加密策略，不再要求获取硬件ID，而改为采用 randomUUID。
但未经测试，还不确定是否解决了这个问题。

**Comment by cdfmlr** [comment]
经过测试，我们认为该问题已经解决
